/**
 * Batch 2: Numerical Reasoning items 036 to 065 (30 items)
 * Skills: pourcentage, ratio, moyenne-ponderee, variation, taux-croissance, analyse-budgetaire
 * Mathematical precision, French typography (comma decimals, 'euros', '12,5 %').
 */

const NOW = new Date().toISOString();
const REVIEWER = "hdjebar";

export const numericBatch2 = [
  {
    id: "numeric-calc-036",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Quel est le montant de l'aide accordée pour un projet d'énergie renouvelable de 150 000 euros subventionné à 30 % ?",
    stimulus: "Projet d'installation photovoltaïque communale.\nCoût total éligible : 150 000 euros.\nTaux d'intervention de l'État : 30 %.",
    options: ["45 000 euros", "30 000 euros", "50 000 euros", "40 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 150 000 × 0,30 = 45 000 euros.",
      "30 000 euros correspondrait à un taux de 20 %.",
      "50 000 euros correspondrait à un tiers (33,3 %).",
      "40 000 euros résulte d'une erreur d'évaluation."
    ],
    explanation: "Le montant de la subvention s'obtient en multipliant le montant éligible par le taux : 150 000 × 0,30 = 45 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-037",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Quel est le taux de variation des dépenses de personnel entre 2024 et 2025 ?",
    stimulus: "Budget de fonctionnement d'un établissement public :\nDépenses de personnel 2024 : 800 000 euros.\nDépenses de personnel 2025 : 880 000 euros.",
    options: ["+10,0 %", "+8,0 %", "+12,5 %", "+9,1 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (880 000 - 800 000) / 800 000 = 80 000 / 800 000 = +10,0 %.",
      "+8,0 % correspond à une confusion avec l'écart brut de 80 000.",
      "+12,5 % correspond au calcul inversé 100/80.",
      "+9,1 % correspondrait au calcul rapporté à la valeur finale (80/880)."
    ],
    explanation: "La variation relative est égale à (Valeur finale - Valeur initiale) / Valeur initiale = (880 000 - 800 000) / 800 000 = +10,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-038",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Quel est le coût moyen pondéré d'une journée de formation par stagiaire ?",
    stimulus: "Session A : 20 participants à 100 euros par jour.\nSession B : 30 participants à 150 euros par jour.",
    options: ["130 euros", "125 euros", "120 euros", "135 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : ((20 × 100) + (30 × 150)) / 50 = (2 000 + 4 500) / 50 = 6 500 / 50 = 130 euros.",
      "125 euros est la simple moyenne arithmétique non pondérée de 100 et 150.",
      "120 euros sous-estime le poids de la session B.",
      "135 euros surestime le coût moyen."
    ],
    explanation: "Coût total = (20 × 100) + (30 × 150) = 2 000 + 4 500 = 6 500 euros. Nombre total de stagiaires = 50. Moyenne pondérée = 6 500 / 50 = 130 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-039",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Une enveloppe de 120 000 euros est répartie entre les directions A et B dans le ratio 3:2. Quelle est la part de la direction A ?",
    stimulus: "Crédits de relance informatique : 120 000 euros à ventiler.\nRatio d'attribution Direction A : Direction B = 3 : 2.",
    options: ["72 000 euros", "48 000 euros", "60 000 euros", "80 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total des parts = 3 + 2 = 5 parts. Valeur d'une part = 120 000 / 5 = 24 000 euros. Direction A = 3 × 24 000 = 72 000 euros.",
      "48 000 euros correspond à la part de la direction B (2 parts).",
      "60 000 euros correspondrait à un partage égalitaire 1:1.",
      "80 000 euros correspondrait à un ratio 2:1."
    ],
    explanation: "Le ratio 3:2 comporte 5 parts au total (3 + 2). Chaque part vaut 120 000 / 5 = 24 000 euros. La direction A reçoit 3 parts, soit 72 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-040",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 90,
    prompt: "Une commune compte 10 000 habitants en 2023. Sa population augmente de 5,0 % en 2024, puis de 4,0 % en 2025. Quelle est sa population au terme de 2025 ?",
    stimulus: "Recensement communal :\nPopulation 2023 : 10 000 habitants.\nCroissance en 2024 : +5,0 %.\nCroissance en 2025 : +4,0 %.",
    options: ["10 920 habitants", "10 900 habitants", "10 950 habitants", "10 880 habitants"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 10 000 × 1,05 = 10 500, puis 10 500 × 1,04 = 10 920 habitants.",
      "10 900 habitants résulte de l'addition simple sans composition (5 % + 4 % = 9 %).",
      "10 950 habitants surestime le produit cumulé.",
      "10 880 habitants sous-estime la croissance."
    ],
    explanation: "La croissance cumulée est multiplicative : 10 000 × 1,05 = 10 500 habitants au terme de 2024. Puis 10 500 × 1,04 = 10 920 habitants fin 2025.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-041",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Quel est le taux de consommation du budget d'investissement au 30 septembre ?",
    stimulus: "Suivi budgétaire annuel :\nCrédits votés : 2 000 000 euros.\nCrédits ordonnancés au 30 septembre : 1 400 000 euros.",
    options: ["70,0 %", "65,0 %", "75,0 %", "60,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 1 400 000 / 2 000 000 = 0,70 soit 70,0 %.",
      "65,0 % correspondrait à 1 300 000 euros.",
      "75,0 % correspondrait à 1 500 000 euros.",
      "60,0 % correspondrait à 1 200 000 euros."
    ],
    explanation: "Taux de consommation = Dépenses exécutées / Crédits votés = 1 400 000 / 2 000 000 = 70,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-042",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Sur un effectif de 400 agents, 15 % travaillent à temps partiel et parmi ceux-ci, 40 % travaillent à mi-temps exact. Combien d'agents travaillent à mi-temps exact ?",
    stimulus: "Direction générale de l'administration :\nEffectif global : 400 agents.\nTaux de temps partiel : 15 %.\nPart du mi-temps parmi les temps partiels : 40 %.",
    options: ["24 agents", "20 agents", "28 agents", "30 agents"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 400 × 0,15 = 60 agents à temps partiel ; 60 × 0,40 = 24 agents.",
      "20 agents correspondrait à un tiers des temps partiels.",
      "28 agents résulte d'un calcul erroné.",
      "30 agents correspondrait à 50 % des temps partiels."
    ],
    explanation: "Agents à temps partiel : 400 × 0,15 = 60. Agents à mi-temps exact : 60 × 0,40 = 24 agents.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-043",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 80,
    prompt: "Le nombre d'usagers accueillis est passé de 2 500 à 2 000 au guichet. Quel est le pourcentage de baisse ?",
    stimulus: "Fréquentation du guichet d'accueil citoyen :\nSemestre 1 : 2 500 usagers.\nSemestre 2 : 2 000 usagers.",
    options: ["-20,0 %", "-25,0 %", "-15,0 %", "-18,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (2 000 - 2 500) / 2 500 = -500 / 2 500 = -0,20 soit -20,0 %.",
      "-25,0 % correspondrait à rapporter la baisse de 500 à la valeur d'arrivée (500 / 2 000).",
      "-15,0 % sous-estime l'ampleur de la diminution.",
      "-18,0 % résulte d'une erreur de calcul."
    ],
    explanation: "La variation en pourcentage est calculée par rapport à la valeur de départ : (2 000 - 2 500) / 2 500 = -500 / 2 500 = -20,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-044",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Le ratio hommes/femmes parmi les candidats reçus est de 3:5. Si 40 candidats sont admis au total, combien de femmes ont été reçues ?",
    stimulus: "Résultats du concours administratif :\nNombre total d'admis : 40 candidats.\nRatio Hommes / Femmes : 3 : 5.",
    options: ["25 candidates", "15 candidates", "20 candidates", "30 candidates"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total parts = 3 + 5 = 8 parts. Valeur d'une part = 40 / 8 = 5. Femmes = 5 × 5 = 25 candidates.",
      "15 candidats correspond au nombre d'hommes (3 parts × 5).",
      "20 candidates supposerait une stricte parité 1:1.",
      "30 candidates correspondrait à un ratio 1:3."
    ],
    explanation: "Le ratio comprend 8 parts égales (3 + 5 = 8). Une part équivaut à 40 / 8 = 5 candidats. Les femmes représentent 5 parts, soit 5 × 5 = 25 candidates.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-045",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 80,
    prompt: "Quelle est la note finale globale pondérée d'un candidat à l'examen professionnel ?",
    stimulus: "Épreuve écrite (coefficient 3) : 12 / 20.\nÉpreuve orale (coefficient 2) : 15 / 20.",
    options: ["13,2 / 20", "13,5 / 20", "13,0 / 20", "14,0 / 20"],
    correctIndex: 0,
    optionRationales: [
      "Correct : ((12 × 3) + (15 × 2)) / (3 + 2) = (36 + 30) / 5 = 66 / 5 = 13,2 / 20.",
      "13,5 / 20 est la moyenne arithmétique simple non pondérée (12 + 15)/2.",
      "13,0 / 20 sous-évalue la note orale.",
      "14,0 / 20 surpondère indûment l'épreuve orale."
    ],
    explanation: "Total des points = (12 × 3) + (15 × 2) = 36 + 30 = 66 points. Total des coefficients = 3 + 2 = 5. Note moyenne pondérée = 66 / 5 = 13,2 / 20.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-046",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Quel est le solde budgétaire disponible non engagé en fin d'exercice ?",
    stimulus: "Dotation initiale : 500 000 euros.\nEngagements réalisés : 420 000 euros.\nFactures payées : 380 000 euros.",
    options: ["80 000 euros", "120 000 euros", "40 000 euros", "100 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : solde disponible non engagé = Dotation (500 000) - Engagements (420 000) = 80 000 euros.",
      "120 000 euros confond le solde disponible avec le solde non payé (500 000 - 380 000).",
      "40 000 euros correspond à l'écart entre engagements et paiements (420 000 - 380 000).",
      "100 000 euros résulte d'une mauvaise lecture des chiffres."
    ],
    explanation: "La disponibilité budgétaire se mesure par rapport aux engagements juridiques pris : 500 000 - 420 000 = 80 000 euros de crédits libres.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-047",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Un prix d'achat public hors taxes est de 80 000 euros. Le taux de TVA applicable est de 17,0 %. Quel est le montant toutes taxes comprises (TTC) ?",
    stimulus: "Acquisition de matériel roulant :\nMontant hors taxes : 80 000 euros.\nTaux normal de TVA au Luxembourg : 17,0 %.",
    options: ["93 600 euros", "92 000 euros", "94 200 euros", "91 500 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : TVA = 80 000 × 0,17 = 13 600 euros ; Total TTC = 80 000 + 13 600 = 93 600 euros.",
      "92 000 euros correspondrait à une TVA de 15,0 % (12 000 euros).",
      "94 200 euros surestime le montant de la taxe.",
      "91 500 euros sous-estime le montant de la taxe."
    ],
    explanation: "Montant TTC = HT × (1 + Taux TVA) = 80 000 × 1,17 = 93 600 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-048",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Si le trafic des passagers d'une ligne de tramway progresse de 2,0 % par mois de manière constante, quelle est la progression sur 2 mois ?",
    stimulus: "Fréquentation du réseau métropolitain :\nCroissance mensuelle régulière : +2,0 % par mois.",
    options: ["+4,04 %", "+4,00 %", "+4,20 %", "+3,98 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 1,02 × 1,02 = 1,0404 soit une hausse globale de +4,04 %.",
      "+4,00 % est la somme linéaire qui omet les intérêts composés.",
      "+4,20 % surestime l'effet cumulé.",
      "+3,98 % sous-estime la croissance."
    ],
    explanation: "Le coefficient multiplicateur sur 2 mois est 1,02 × 1,02 = 1,0404, soit un taux d'accroissement global de (1,0404 - 1) × 100 = +4,04 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-049",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Sur une ligne budgétaire de 90 000 euros, les dépenses de matériel et de prestation externe sont dans un rapport de 4 pour 5. Quel montant revient au matériel ?",
    stimulus: "Budget de service : 90 000 euros.\nRépartition Matériel : Prestations = 4 : 5.",
    options: ["40 000 euros", "50 000 euros", "45 000 euros", "36 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total des parts = 4 + 5 = 9 parts. Une part = 90 000 / 9 = 10 000 euros. Matériel = 4 × 10 000 = 40 000 euros.",
      "50 000 euros correspond aux prestations externes (5 parts).",
      "45 000 euros correspondrait à une division en deux parts égales.",
      "36 000 euros résulte d'un mauvais calcul de part."
    ],
    explanation: "Total des parts = 4 + 5 = 9. Chaque part vaut 90 000 / 9 = 10 000 euros. La composante matériel représente 4 parts, soit 40 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-050",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Une administration accorde une remise commerciale de 12,0 % sur un catalogue d'équipements facturé à 25 000 euros. Quel est le montant net à payer ?",
    stimulus: "Marché de mobilier de bureau :\nMontant brut catalogue : 25 000 euros.\nRemise négociée : 12,0 %.",
    options: ["22 000 euros", "21 500 euros", "22 500 euros", "23 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : remise = 25 000 × 0,12 = 3 000 euros ; Net = 25 000 - 3 000 = 22 000 euros.",
      "21 500 euros déduit une remise excessive de 14 %.",
      "22 500 euros applique une remise de 10 % seulement.",
      "23 000 euros applique une remise de 8 % seulement."
    ],
    explanation: "Montant net = Montant brut × (1 - Remise) = 25 000 × (1 - 0,12) = 25 000 × 0,88 = 22 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-051",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Quel est le salaire moyen brut mensuel de ce service de 10 agents ?",
    stimulus: "Répartition salariale du service :\n6 agents de catégorie B : 4 000 euros bruts.\n4 agents de catégorie A : 6 000 euros bruts.",
    options: ["4 800 euros", "5 000 euros", "4 600 euros", "5 200 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : ((6 × 4 000) + (4 × 6 000)) / 10 = (24 000 + 24 000) / 10 = 48 000 / 10 = 4 800 euros.",
      "5 000 euros est la moyenne arithmétique simple non pondérée (4 000 + 6 000)/2.",
      "4 600 euros sous-évalue la part des cadres de catégorie A.",
      "5 200 euros surévalue la masse salariale globale."
    ],
    explanation: "Masse salariale totale = (6 × 4 000) + (4 × 6 000) = 24 000 + 24 000 = 48 000 euros. Salaire moyen = 48 000 / 10 = 4 800 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-052",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Quel est le taux d'accroissement du nombre de télédéclarations entre les deux exercices ?",
    stimulus: "Plateforme citoyenne en ligne :\nTélédéclarations année N-1 : 40 000 dossiers.\nTélédéclarations année N : 52 000 dossiers.",
    options: ["+30,0 %", "+25,0 %", "+35,0 %", "+28,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (52 000 - 40 000) / 40 000 = 12 000 / 40 000 = +0,30 soit +30,0 %.",
      "+25,0 % correspondrait à 50 000 dossiers (+10 000).",
      "+35,0 % correspondrait à 54 000 dossiers.",
      "+28,0 % résulte d'une erreur d'arrondi."
    ],
    explanation: "Variation relative = (52 000 - 40 000) / 40 000 = 12 000 / 40 000 = +30,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-053",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Si les dépenses réelles dépassent les prévisions de 8,0 % sur un budget prévu de 650 000 euros, quel est le dépassement en valeur absolue ?",
    stimulus: "Exécution des travaux publics :\nBudget prévisionnel approuvé : 650 000 euros.\nÉcart constaté : dépassement de 8,0 %.",
    options: ["52 000 euros", "48 000 euros", "56 000 euros", "50 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 650 000 × 0,08 = 52 000 euros de surcoût.",
      "48 000 euros sous-estime le montant (correspondrait à ~7,4 %).",
      "56 000 euros surestime le dépassement.",
      "50 000 euros est une estimation arrondie inexacte."
    ],
    explanation: "Le dépassement en euros est égal à 650 000 × 0,08 = 52 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-054",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Dans un hôpital de 300 lits, le ratio lits de chirurgie / lits de médecine est de 1:2. Combien de lits sont dédiés à la chirurgie ?",
    stimulus: "Capacité d'accueil hospitalière :\nNombre total de lits : 300.\nRatio Chirurgie : Médecine = 1 : 2.",
    options: ["100 lits", "150 lits", "200 lits", "75 lits"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total parts = 1 + 2 = 3. Valeur d'une part = 300 / 3 = 100 lits de chirurgie.",
      "150 lits supposerait une répartition égale 1:1.",
      "200 lits correspond aux lits de médecine (2 parts).",
      "75 lits correspondrait à un quart de la capacité."
    ],
    explanation: "Le ratio 1:2 totalise 3 parts égales. Chaque part représente 300 / 3 = 100 lits. La chirurgie disposant d'une part, elle compte 100 lits.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-055",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 80,
    prompt: "Un investissement de 200 000 euros rapporte 15 000 euros d'économies annuelles d'énergie. Quel est le taux de rendement annuel de l'opération ?",
    stimulus: "Audit énergétique du siège administratif :\nCoût des travaux d'isolation : 200 000 euros.\nÉconomie nette d'exploitation par an : 15 000 euros.",
    options: ["7,5 %", "8,0 %", "7,0 %", "6,5 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 15 000 / 200 000 = 0,075 soit 7,5 %.",
      "8,0 % correspondrait à 16 000 euros d'économies.",
      "7,0 % correspondrait à 14 000 euros d'économies.",
      "6,5 % correspondrait à 13 000 euros d'économies."
    ],
    explanation: "Taux de rendement annuel = Économie annuelle / Investissement initial = 15 000 / 200 000 = 7,5 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-056",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Un traitement indiciaire subit deux hausses successives de 2,5 % au cours de l'année. Quel est le pourcentage total d'augmentation ?",
    stimulus: "Indicateurs salariaux dans la fonction publique :\n1re tranche indiciaire : +2,5 %.\n2e tranche indiciaire : +2,5 %.",
    options: ["+5,0625 %", "+5,0000 %", "+5,1250 %", "+4,9750 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 1,025 × 1,025 = 1,050625, soit une augmentation globale de +5,0625 %.",
      "+5,0000 % est la somme arithmétique simple qui omet l'effet de composition.",
      "+5,1250 % surestime l'effet cumulé.",
      "+4,9750 % sous-estime le résultat."
    ],
    explanation: "Multiplicateur composé = 1,025 × 1,025 = 1,050625, traduisant une augmentation exacte de +5,0625 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-057",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Quel est l'écart en pourcentage entre le budget prévisionnel et les dépenses réelles ?",
    stimulus: "Direction de l'environnement :\nBudget prévisionnel : 500 000 euros.\nDépenses réelles constatées : 475 000 euros.",
    options: ["-5,0 %", "-4,0 %", "-6,0 %", "-5,5 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (475 000 - 500 000) / 500 000 = -25 000 / 500 000 = -0,05 soit -5,0 %.",
      "-4,0 % correspondrait à une économie de 20 000 euros.",
      "-6,0 % correspondrait à une économie de 30 000 euros.",
      "-5,5 % résulte d'une erreur d'évaluation."
    ],
    explanation: "Variation relative = (475 000 - 500 000) / 500 000 = -25 000 / 500 000 = -5,0 % (sous-consommation de 5 %).",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-058",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Dans un service comptant 80 personnes, 65 % ont suivi la formation obligatoire à la sécurité. Combien d'agents n'ont PAS encore suivi la session ?",
    stimulus: "Service logistique ministériel :\nEffectif total : 80 agents.\nTaux de participation constaté : 65 %.",
    options: ["28 agents", "24 agents", "32 agents", "26 agents"],
    correctIndex: 0,
    optionRationales: [
      "Correct : agents non formés = 100 % - 65 % = 35 % ; 80 × 0,35 = 28 agents.",
      "24 agents correspondrait à 30 % d'agents non formés.",
      "32 agents correspondrait à 40 % d'agents non formés.",
      "26 agents résulte d'un calcul inexact."
    ],
    explanation: "Le pourcentage d'agents restants est 100 % - 65 % = 35 %. 80 × 0,35 = 28 agents à former.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-059",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Une flotte de 180 véhicules de service comprend 2 véhicules électriques pour 1 véhicule thermique. Combien de véhicules électriques compte le parc ?",
    stimulus: "Parc automobile administratif :\nTotal du parc : 180 véhicules.\nRatio Électrique : Thermique = 2 : 1.",
    options: ["120 véhicules", "90 véhicules", "60 véhicules", "140 véhicules"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total parts = 2 + 1 = 3 parts. Une part = 180 / 3 = 60. Électriques = 2 × 60 = 120 véhicules.",
      "90 véhicules supposerait une parité stricte (1:1).",
      "60 véhicules correspond au nombre de véhicules thermiques (1 part).",
      "140 véhicules surestime la part électrique."
    ],
    explanation: "Le ratio 2:1 totalise 3 parts. Une part vaut 180 / 3 = 60. Les véhicules électriques représentent 2 parts, soit 2 × 60 = 120 véhicules.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-060",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 80,
    prompt: "Quel est le coût moyen de traitement d'un dossier administratif ?",
    stimulus: "Service d'état civil communal :\nDépenses opérationnelles totales : 180 000 euros.\nNombre de dossiers traités : 4 500 dossiers.",
    options: ["40 euros", "35 euros", "45 euros", "50 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 180 000 / 4 500 = 40 euros par dossier.",
      "35 euros sous-estime le ratio de coût.",
      "45 euros surestime le ratio de coût.",
      "50 euros correspondrait à un budget de 225 000 euros."
    ],
    explanation: "Coût unitaire moyen = Dépenses totales / Volume traité = 180 000 / 4 500 = 40 euros par dossier.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-061",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Sur une enveloppe globale de 600 000 euros, 45 % sont alloués aux travaux de voirie et 25 % aux espaces verts. Quel montant reste disponible pour les autres actions ?",
    stimulus: "Budget participatif communal :\nEnveloppe totale : 600 000 euros.\nVoirie : 45 %.\nEspaces verts : 25 %.",
    options: ["180 000 euros", "150 000 euros", "200 000 euros", "160 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : part restante = 100 % - (45 % + 25 %) = 30 % ; 600 000 × 0,30 = 180 000 euros.",
      "150 000 euros correspondrait à 25 % restants.",
      "200 000 euros correspondrait à un tiers du budget.",
      "160 000 euros résulte d'une erreur de calcul."
    ],
    explanation: "Les deux postes mobilisent 45 % + 25 % = 70 % de l'enveloppe. Il reste 30 % à attribuer : 600 000 × 0,30 = 180 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-062",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 80,
    prompt: "Le volume de déchets ménagers non recyclés a baissé de 800 tonnes à 680 tonnes en un an. Quel est le pourcentage de réduction constaté ?",
    stimulus: "Indicateurs environnementaux communaux :\nDéchets non recyclés an 1 : 800 tonnes.\nDéchets non recyclés an 2 : 680 tonnes.",
    options: ["-15,0 %", "-12,0 %", "-18,0 %", "-14,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (680 - 800) / 800 = -120 / 800 = -0,15 soit -15,0 %.",
      "-12,0 % correspondrait à une baisse de 96 tonnes.",
      "-18,0 % correspondrait à une baisse de 144 tonnes.",
      "-14,0 % est un calcul inexact."
    ],
    explanation: "Variation relative = (680 - 800) / 800 = -120 / 800 = -15,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-063",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Quel est le délai moyen de réponse de l'administration pour ces 100 réclamations ?",
    stimulus: "Qualité de service usagers :\n40 réclamations traitées en 5 jours.\n60 réclamations traitées en 10 jours.",
    options: ["8,0 jours", "7,5 jours", "8,5 jours", "7,0 jours"],
    correctIndex: 0,
    optionRationales: [
      "Correct : ((40 × 5) + (60 × 10)) / 100 = (200 + 600) / 100 = 800 / 100 = 8,0 jours.",
      "7,5 jours est la moyenne arithmétique simple non pondérée (5 + 10)/2.",
      "8,5 jours surévalue le poids des réclamations longues.",
      "7,0 jours sous-évalue le délai global."
    ],
    explanation: "Délai total cumulé = (40 × 5) + (60 × 10) = 200 + 600 = 800 jours. Délai moyen = 800 / 100 = 8,0 jours.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-064",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Le ratio agents de terrain / agents administratifs dans un service de police est de 5:1. Pour 120 agents au total, combien d'agents exercent sur le terrain ?",
    stimulus: "Effectifs du corps de police locale :\nTotal général : 120 agents.\nRatio Terrain : Administration = 5 : 1.",
    options: ["100 agents", "90 agents", "105 agents", "96 agents"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total parts = 5 + 1 = 6 parts. Une part = 120 / 6 = 20. Terrain = 5 × 20 = 100 agents.",
      "90 agents correspondrait à un ratio 3:1.",
      "105 agents ne correspond pas à une division exacte en 6 parts.",
      "96 agents correspondrait à 80 % de l'effectif."
    ],
    explanation: "Le ratio 5:1 totalise 6 parts. Chaque part équivaut à 120 / 6 = 20 agents. Les agents de terrain représentant 5 parts, ils sont au nombre de 5 × 20 = 100 agents.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-065",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Une subvention de recherche de 100 000 euros croît de 10,0 % par an pendant deux années consécutives. Quel est son montant final ?",
    stimulus: "Fonds national pour l'innovation scientifique :\nDotation de départ : 100 000 euros.\nIndexation annuelle : +10,0 % par an sur 2 ans.",
    options: ["121 000 euros", "120 000 euros", "122 000 euros", "119 500 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 100 000 × 1,10 × 1,10 = 100 000 × 1,21 = 121 000 euros.",
      "120 000 euros résulte d'une addition linéaire simple (+10 % + 10 % = +20 %).",
      "122 000 euros surestime le résultat composé.",
      "119 500 euros sous-estime la croissance."
    ],
    explanation: "La croissance cumulée est égale à 100 000 × (1,10)^2 = 100 000 × 1,21 = 121 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  }
];
