/**
 * Batch 3: Numerical Reasoning items 066 to 100 (35 items)
 * Skills: pourcentage, variation, ratio-proportion, moyenne, operations-simples
 * French typography (comma decimals, 'euros', '12,5 %').
 */

const NOW = new Date().toISOString();
const REVIEWER = "hdjebar";

export const numericBatch3 = [
  {
    id: "numeric-calc-066",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Sur une enveloppe de 240 000 euros, 35 % sont alloués aux rénovations thermiques. Quel est le montant de ce crédit ?",
    stimulus: "Plan climat communal :\nEnveloppe totale disponible : 240 000 euros.\nPart réservée à la rénovation thermique : 35 %.",
    options: ["84 000 euros", "72 000 euros", "90 000 euros", "80 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 240 000 × 0,35 = 84 000 euros.",
      "72 000 euros correspondrait à un taux de 30 %.",
      "90 000 euros correspondrait à un taux de 37,5 %.",
      "80 000 euros correspondrait à un tiers du budget."
    ],
    explanation: "Montant alloué = 240 000 × 0,35 = 84 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-067",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Quel est le taux de variation des dépenses énergétiques entre l'année N-1 et l'année N ?",
    stimulus: "Facture énergétique de la cité administrative :\nAnnée N-1 : 120 000 euros.\nAnnée N : 102 000 euros.",
    options: ["-15,0 %", "-12,0 %", "-18,0 %", "-14,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (102 000 - 120 000) / 120 000 = -18 000 / 120 000 = -0,15 soit -15,0 %.",
      "-12,0 % correspondrait à une dépense de 105 600 euros.",
      "-18,0 % confond l'écart brut de 18 000 avec le pourcentage.",
      "-14,0 % résulte d'une erreur d'évaluation."
    ],
    explanation: "La variation relative est (102 000 - 120 000) / 120 000 = -18 000 / 120 000 = -15,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-068",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Quel est le coût moyen pondéré d'un audit de conformité par unité administrative ?",
    stimulus: "Campagne d'audits internes :\nGroupe 1 : 10 unités auditées au coût de 3 000 euros chacune.\nGroupe 2 : 15 unités auditées au coût de 4 000 euros chacune.",
    options: ["3 600 euros", "3 500 euros", "3 800 euros", "3 400 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : ((10 × 3 000) + (15 × 4 000)) / 25 = (30 000 + 60 000) / 25 = 90 000 / 25 = 3 600 euros.",
      "3 500 euros est la moyenne arithmétique simple non pondérée (3 000 + 4 000)/2.",
      "3 800 euros surévalue le poids du groupe 2.",
      "3 400 euros sous-évalue le coût global moyen."
    ],
    explanation: "Coût total = 30 000 + 60 000 = 90 000 euros. Nombre d'unités = 25. Moyenne pondérée = 90 000 / 25 = 3 600 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-069",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Une subvention de 150 000 euros est répartie entre les projets Vert et Bleu selon un ratio 2:3. Quelle est la part du projet Bleu ?",
    stimulus: "Fonds pour la transition écologique :\nMontant total : 150 000 euros.\nClé de répartition Projet Vert : Projet Bleu = 2 : 3.",
    options: ["90 000 euros", "60 000 euros", "75 000 euros", "100 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total parts = 2 + 3 = 5. Une part = 150 000 / 5 = 30 000 euros. Projet Bleu = 3 × 30 000 = 90 000 euros.",
      "60 000 euros correspond à la part du projet Vert (2 parts).",
      "75 000 euros supposerait un partage à parts égales 1:1.",
      "100 000 euros correspondrait à un ratio 1:2."
    ],
    explanation: "Le ratio 2:3 comporte 5 parts au total. Chaque part vaut 150 000 / 5 = 30 000 euros. Le projet Bleu recevant 3 parts, son allocation est de 90 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-070",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "operations-simples",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 65,
    prompt: "Quel est le coût total d'acquisition de 80 écrans bureautiques facturés à 175 euros l'unité hors taxes ?",
    stimulus: "Renouvellement du matériel informatique :\nQuantité commandée : 80 écrans.\nPrix unitaire négocié : 175 euros hors taxes.",
    options: ["14 000 euros", "13 500 euros", "14 500 euros", "12 800 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 80 × 175 = 14 000 euros.",
      "13 500 euros sous-estime le total.",
      "14 500 euros surestime le total.",
      "12 800 euros correspondrait à 160 euros l'unité."
    ],
    explanation: "Calcul direct : 80 × 175 = (80 × 100) + (80 × 75) = 8 000 + 6 000 = 14 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-071",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Un investissement de 50 000 euros hors taxes bénéficie d'une remise de 10 % puis est soumis à une TVA de 17,0 %. Quel est le montant net TTC à payer ?",
    stimulus: "Achat d'équipements de sécurité publique :\nPrix catalogue brut : 50 000 euros HT.\nRemise commerciale : 10,0 %.\nTaux de TVA : 17,0 %.",
    options: ["52 650 euros", "53 500 euros", "51 850 euros", "54 200 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : montant après remise = 50 000 × 0,90 = 45 000 euros HT ; Montant TTC = 45 000 × 1,17 = 52 650 euros.",
      "53 500 euros applique la TVA sur le montant brut avant remise (50 000 × 1,17 - 5 000).",
      "51 850 euros correspondrait à une TVA de 15,2 %.",
      "54 200 euros surestime le calcul final."
    ],
    explanation: "Prix remisé HT = 50 000 × 0,90 = 45 000 euros. Avec TVA de 17 % : 45 000 × 1,17 = 52 650 euros TTC.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-072",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Un effectif de 500 agents progresse de 6,0 % la première année, puis diminue de 5,0 % la seconde année. Quel est l'effectif final ?",
    stimulus: "Évolution pluriannuelle des effectifs municipaux :\nEffectif de départ : 500 agents.\nAnnée 1 : hausse de +6,0 %.\nAnnée 2 : baisse de -5,0 %.",
    options: ["503,5 agents", "505,0 agents", "500,0 agents", "508,0 agents"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 500 × 1,06 = 530 agents en an 1 ; 530 × 0,95 = 503,5 agents.",
      "505,0 agents résulterait de la simple addition linéaire (+6 % - 5 % = +1 %).",
      "500,0 agents supposerait que la hausse et la baisse se neutralisent parfaitement.",
      "508,0 agents surestime l'effectif résiduel."
    ],
    explanation: "Multiplicateur composé = 1,06 × 0,95 = 1,007. Effectif final = 500 × 1,007 = 503,5 agents (soit une hausse nette de 0,7 % et non 1,0 %).",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-073",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Quel est le montant moyen des quatre subventions accordées aux associations culturelles ?",
    stimulus: "Subventions attribuées par le conseil communal :\nAssociation A : 12 000 euros.\nAssociation B : 18 000 euros.\nAssociation C : 15 000 euros.\nAssociation D : 23 000 euros.",
    options: ["17 000 euros", "16 500 euros", "17 500 euros", "18 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (12 000 + 18 000 + 15 000 + 23 000) / 4 = 68 000 / 4 = 17 000 euros.",
      "16 500 euros sous-estime la somme moyenne.",
      "17 500 euros surestime la somme moyenne.",
      "18 000 euros correspondrait à un total de 72 000 euros."
    ],
    explanation: "Total cumulé = 12 000 + 18 000 + 15 000 + 23 000 = 68 000 euros. Moyenne arithmétique = 68 000 / 4 = 17 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-074",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 80,
    prompt: "Dans un concours d'accès, 3 candidats sur 8 admissibles sont finalement déclarés lauréats. Si 48 candidats sont admissibles, combien sont admis ?",
    stimulus: "Jury de concours administratif territorial :\nNombre de candidats admissibles : 48.\nTaux de réussite final : ratio de 3 lauréats pour 8 admissibles.",
    options: ["18 admis", "16 admis", "20 admis", "24 admis"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 48 × (3 / 8) = 6 × 3 = 18 candidats admis.",
      "16 candidats correspondrait à un ratio de 1/3 (16 sur 48).",
      "20 candidats surestime le nombre d'admis.",
      "24 candidats correspondrait à une parité de 50 % (1 sur 2)."
    ],
    explanation: "Nombre d'admis = 48 × (3/8) = (48 / 8) × 3 = 6 × 3 = 18 candidats.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-075",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Une administration réalise 18 000 euros d'économies sur une ligne budgétaire dotée de 300 000 euros. Quel est le pourcentage d'économie réalisé ?",
    stimulus: "Bilan annuel d'exploitation :\nBudget alloué : 300 000 euros.\nÉconomie nette constatée : 18 000 euros.",
    options: ["6,0 %", "5,0 %", "7,0 %", "5,5 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 18 000 / 300 000 = 0,06 soit 6,0 %.",
      "5,0 % correspondrait à 15 000 euros d'économies.",
      "7,0 % correspondrait à 21 000 euros d'économies.",
      "5,5 % correspondrait à 16 500 euros d'économies."
    ],
    explanation: "Taux d'économie = 18 000 / 300 000 = 6 / 100 = 6,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-076",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Le délai moyen de traitement d'un dossier passe de 25 jours à 20 jours. Quel est le taux de réduction du délai constaté ?",
    stimulus: "Indicateur de performance des services d'urbanisme :\nDélai initial : 25 jours.\nNouveau délai moyen constaté : 20 jours.",
    options: ["-20,0 %", "-25,0 %", "-15,0 %", "-18,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (20 - 25) / 25 = -5 / 25 = -0,20 soit -20,0 %.",
      "-25,0 % correspondrait à rapporter le gain de 5 jours à la valeur finale (5 / 20).",
      "-15,0 % sous-estime l'amélioration de productivité.",
      "-18,0 % résulte d'une erreur de calcul."
    ],
    explanation: "Variation relative = (20 - 25) / 25 = -5 / 25 = -20,0 % de réduction de temps.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-077",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "operations-simples",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 65,
    prompt: "Combien d'agents au total composent le pôle logistique de cette direction ?",
    stimulus: "Répartition des équipes de soutien logistique :\nÉquipe Maintenance : 14 agents.\nÉquipe Accueil et Courrier : 12 agents.\nÉquipe Chauffeurs : 8 agents.\nÉquipe Reprographie : 6 agents.",
    options: ["40 agents", "38 agents", "42 agents", "36 agents"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 14 + 12 + 8 + 6 = 40 agents au total.",
      "38 agents oublie 2 agents dans le décompte.",
      "42 agents compte 2 agents en trop.",
      "36 agents omet une équipe partielle."
    ],
    explanation: "Somme directe des composantes : 14 + 12 + 8 + 6 = 40 agents.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-078",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Sur 1 200 réclamations annuelles, 75 % sont traitées sous 48 heures. Parmi le solde restant, 60 % sont réglées sous une semaine. Combien de dossiers restent non traités au bout d'une semaine ?",
    stimulus: "Qualité de l'écoute usagers :\nTotal réclamations : 1 200.\nTraitées sous 48h : 75 %.\nTraitées entre 48h et 7 jours : 60 % du solde restant.",
    options: ["120 réclamations", "100 réclamations", "150 réclamations", "80 réclamations"],
    correctIndex: 0,
    optionRationales: [
      "Correct : solde après 48h = 1 200 × 0,25 = 300 dossiers ; non traités à 7 jours = 300 × 0,40 = 120 réclamations.",
      "100 réclamations sous-estime le résidu.",
      "150 réclamations supposerait que seulement 50 % du solde a été traité.",
      "80 réclamations surestime l'apurement des dossiers."
    ],
    explanation: "Dossiers non traités sous 48h = 1 200 × (1 - 0,75) = 300. Parmi ces 300, 40 % restent en attente après 7 jours : 300 × 0,40 = 120 dossiers.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-079",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 80,
    prompt: "Un candidat obtient 14 sur 20 à l'épreuve écrite (coefficient 4) et 11 sur 20 à l'épreuve orale (coefficient 2). Quelle est sa moyenne générale d'admission ?",
    stimulus: "Barème des épreuves de sélection :\nÉpreuve écrite : coefficient 4, note 14 / 20.\nÉpreuve orale : coefficient 2, note 11 / 20.",
    options: ["13,0 / 20", "12,5 / 20", "13,5 / 20", "12,0 / 20"],
    correctIndex: 0,
    optionRationales: [
      "Correct : ((14 × 4) + (11 × 2)) / (4 + 2) = (56 + 22) / 6 = 78 / 6 = 13,0 / 20.",
      "12,5 / 20 est la moyenne arithmétique simple non pondérée (14 + 11)/2.",
      "13,5 / 20 surpondère indûment l'épreuve écrite.",
      "12,0 / 20 sous-évalue la note globale."
    ],
    explanation: "Points totaux = (14 × 4) + (11 × 2) = 56 + 22 = 78 points. Total des coefficients = 4 + 2 = 6. Moyenne = 78 / 6 = 13,0 / 20.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-080",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Le ratio agents de catégorie A / catégorie B dans un service est de 1:4. Si le service compte 8 agents de catégorie A, quel est le nombre d'agents de catégorie B ?",
    stimulus: "Structure hiérarchique du service juridique :\nRatio Catégorie A : Catégorie B = 1 : 4.\nNombre d'agents de catégorie A : 8 agents.",
    options: ["32 agents", "28 agents", "36 agents", "40 agents"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 8 × 4 = 32 agents de catégorie B.",
      "28 agents sous-estime l'effectif.",
      "36 agents surestime l'effectif.",
      "40 agents correspondrait à l'effectif total A + B (8 + 32 = 40)."
    ],
    explanation: "La proportion impose 4 agents de catégorie B pour chaque agent de catégorie A : 8 × 4 = 32 agents de catégorie B.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-081",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Un marché de travaux publics de 450 000 euros subit un avenant financier augmentant son coût de 8,0 %. Quel est le nouveau montant total du marché ?",
    stimulus: "Rénovation du groupe scolaire communal :\nMontant initial du marché : 450 000 euros.\nAvenant validé en séance : +8,0 %.",
    options: ["486 000 euros", "480 000 euros", "490 000 euros", "475 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : augmentation = 450 000 × 0,08 = 36 000 euros ; Nouveau total = 450 000 + 36 000 = 486 000 euros.",
      "480 000 euros correspondrait à une hausse de 30 000 euros.",
      "490 000 euros surestime le surcoût de l'avenant.",
      "475 000 euros sous-estime le nouveau total."
    ],
    explanation: "Montant révisé = Montant initial × (1 + Taux) = 450 000 × 1,08 = 486 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-082",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Le volume de courriers papier reçus baisse de 10 000 à 8 500 plis en un an. Quel est le taux de décroissance constaté ?",
    stimulus: "Dématérialisation des flux entrants ministériels :\nVolume initial an N-1 : 10 000 courriers.\nVolume final an N : 8 500 courriers.",
    options: ["-15,0 %", "-12,5 %", "-17,5 %", "-14,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (8 500 - 10 000) / 10 000 = -1 500 / 10 000 = -0,15 soit -15,0 %.",
      "-12,5 % correspondrait à 8 750 courriers.",
      "-17,5 % correspondrait à 8 250 courriers.",
      "-14,0 % résulte d'une erreur d'arrondi."
    ],
    explanation: "Variation en pourcentage = (8 500 - 10 000) / 10 000 = -1 500 / 10 000 = -15,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-083",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "operations-simples",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 65,
    prompt: "Une enveloppe de 72 000 euros est partagée à parts strictement égales entre 6 services déconcentrés. Quel montant revient à chaque service ?",
    stimulus: "Crédits déconcentrés d'action sociale :\nMontant total à ventiler : 72 000 euros.\nNombre de services bénéficiaires : 6 services.",
    options: ["12 000 euros", "11 000 euros", "13 000 euros", "10 500 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 72 000 / 6 = 12 000 euros par service.",
      "11 000 euros sous-estime la part unitaire.",
      "13 000 euros dépasserait l'enveloppe totale.",
      "10 500 euros résulte d'une erreur de division."
    ],
    explanation: "Division simple : 72 000 / 6 = 12 000 euros par entité.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-084",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Sur un parc automobile de 150 véhicules de service, 20 % roulent au biogaz et 40 % sont 100 % électriques. Combien de véhicules au total utilisent ces énergies propres ?",
    stimulus: "Verdissement de la flotte publique :\nNombre total de véhicules : 150.\nPart biogaz : 20 %.\nPart électrique : 40 %.",
    options: ["90 véhicules", "80 véhicules", "100 véhicules", "75 véhicules"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total énergies propres = 20 % + 40 % = 60 % ; 150 × 0,60 = 90 véhicules.",
      "80 véhicules sous-estime le total cumulé.",
      "100 véhicules correspondrait à deux tiers de la flotte.",
      "75 véhicules supposerait exactement la moitié (50 %)."
    ],
    explanation: "La part cumulée d'énergies propres représente 60 % du parc. 150 × 0,60 = 90 véhicules.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-085",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Quel est le nombre moyen d'actes d'état civil délivrés par jour au cours de cette semaine de 5 jours ouvrés ?",
    stimulus: "Activité du service de l'état civil communal :\nLundi : 45 actes.\nMardi : 52 actes.\nMercredi : 38 actes.\nJeudi : 60 actes.\nVendredi : 55 actes.",
    options: ["50 actes", "48 actes", "52 actes", "46 actes"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (45 + 52 + 38 + 60 + 55) / 5 = 250 / 5 = 50 actes par jour.",
      "48 actes sous-estime la moyenne hebdomadaire.",
      "52 actes surestime la moyenne hebdomadaire.",
      "46 actes résulte d'une erreur d'addition."
    ],
    explanation: "Total des actes = 45 + 52 + 38 + 60 + 55 = 250 actes. Moyenne journalière = 250 / 5 = 50 actes.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-086",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Un budget de formation de 80 000 euros est réparti entre trois directions A, B et C dans les proportions 1:2:5. Quel montant revient à la direction C ?",
    stimulus: "Plan de formation ministériel :\nBudget global : 80 000 euros.\nClé de répartition Direction A : B : C = 1 : 2 : 5.",
    options: ["50 000 euros", "40 000 euros", "45 000 euros", "30 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total parts = 1 + 2 + 5 = 8. Une part = 80 000 / 8 = 10 000 euros. Direction C = 5 × 10 000 = 50 000 euros.",
      "40 000 euros correspondrait à la moitié exacte du budget.",
      "45 000 euros ne correspond pas à un multiple entier de part.",
      "30 000 euros sous-estime largement la part de C."
    ],
    explanation: "Le total des parts est de 1 + 2 + 5 = 8 parts. Chaque part équivaut à 80 000 / 8 = 10 000 euros. La direction C recevant 5 parts, sa dotation est de 50 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-087",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Un équipement public a perdu 20,0 % de sa valeur comptable la première année, puis 10,0 % de sa valeur résiduelle la seconde année. Quel est son taux global de dépréciation sur deux ans ?",
    stimulus: "Amortissement comptable des matériels lourds :\nDépréciation An 1 : -20,0 %.\nDépréciation An 2 : -10,0 % sur la valeur résiduelle.",
    options: ["-28,0 %", "-30,0 %", "-25,0 %", "-27,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : valeur résiduelle = (1 - 0,20) × (1 - 0,10) = 0,80 × 0,90 = 0,72 (soit 72 % restants). Dépréciation = 100 % - 72 % = -28,0 %.",
      "-30,0 % résulte de l'addition linéaire simple sans composition (-20 % - 10 %).",
      "-25,0 % sous-estime la dépréciation globale.",
      "-27,0 % résulte d'une erreur de calcul."
    ],
    explanation: "Le coefficient résiduel est 0,80 × 0,90 = 0,72. La dépréciation cumulée s'établit donc à 1 - 0,72 = 0,28, soit -28,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-088",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Le montant d'une taxe communale passe de 400 euros à 460 euros par foyer. Quel est le pourcentage d'augmentation appliqué ?",
    stimulus: "Délibération du conseil communal sur les tarifs d'enlèvement des déchets :\nAncien tarif forfaitaire : 400 euros.\nNouveau tarif voté : 460 euros.",
    options: ["+15,0 %", "+12,0 %", "+18,0 %", "+14,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (460 - 400) / 400 = 60 / 400 = +0,15 soit +15,0 %.",
      "+12,0 % correspondrait à une hausse de 48 euros.",
      "+18,0 % correspondrait à une hausse de 72 euros.",
      "+14,0 % résulte d'une erreur d'évaluation."
    ],
    explanation: "Taux de variation = (460 - 400) / 400 = 60 / 400 = +15,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-089",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "operations-simples",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 65,
    prompt: "Une administration commande 12 imprimantes réseau à 850 euros l'unité hors taxes. Quel est le montant hors taxes de la facture ?",
    stimulus: "Marché public d'équipement bureautique :\nQuantité : 12 imprimantes réseau.\nPrix unitaire HT : 850 euros.",
    options: ["10 200 euros", "10 000 euros", "10 400 euros", "9 800 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 12 × 850 = 12 × 800 + 12 × 50 = 9 600 + 600 = 10 200 euros.",
      "10 000 euros est une estimation arrondie inexacte.",
      "10 400 euros surestime le total.",
      "9 800 euros sous-estime le montant facturé."
    ],
    explanation: "Calcul direct : 12 × 850 = 10 200 euros HT.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-090",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Sur une enveloppe d'aide d'urgence de 500 000 euros, 82 % des crédits ont été engagés. Quel montant reste disponible à l'engagement ?",
    stimulus: "Fonds communal de solidarité d'urgence :\nCrédits votés : 500 000 euros.\nTaux d'engagement constaté : 82 %.",
    options: ["90 000 euros", "80 000 euros", "100 000 euros", "85 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : part disponible = 100 % - 82 % = 18 % ; 500 000 × 0,18 = 90 000 euros.",
      "80 000 euros correspondrait à un taux d'engagement de 84 %.",
      "100 000 euros correspondrait à un taux d'engagement de 80 %.",
      "85 000 euros résulte d'une erreur de calcul."
    ],
    explanation: "Crédits non engagés = 500 000 × (1 - 0,82) = 500 000 × 0,18 = 90 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-091",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Dans un pôle de 50 agents, 30 agents effectuent en moyenne 2 heures supplémentaires par semaine et 20 agents en effectuent 4 heures. Quelle est la moyenne d'heures supplémentaires par agent ?",
    stimulus: "Gestion des temps et activités du service technique :\nGroupe 1 : 30 agents réalisant 2 heures supplémentaires.\nGroupe 2 : 20 agents réalisant 4 heures supplémentaires.",
    options: ["2,8 heures", "3,0 heures", "2,6 heures", "3,2 heures"],
    correctIndex: 0,
    optionRationales: [
      "Correct : ((30 × 2) + (20 × 4)) / 50 = (60 + 80) / 50 = 140 / 50 = 2,8 heures.",
      "3,0 heures est la moyenne simple non pondérée (2 + 4)/2.",
      "2,6 heures sous-évalue la contribution du groupe 2.",
      "3,2 heures surestime le volume moyen."
    ],
    explanation: "Volume total d'heures = (30 × 2) + (20 × 4) = 60 + 80 = 140 heures. Moyenne pondérée = 140 / 50 = 2,8 heures par agent.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-092",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Le ratio agents contractuels / agents fonctionnaires est de 1:3 dans une équipe comptant 60 agents au total. Combien de contractuels l'équipe compte-t-elle ?",
    stimulus: "Composition statutaire des effectifs :\nEffectif global : 60 agents.\nRatio Contractuels : Fonctionnaires = 1 : 3.",
    options: ["15 agents", "20 agents", "12 agents", "18 agents"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total parts = 1 + 3 = 4. Une part = 60 / 4 = 15 agents contractuels.",
      "20 agents correspondrait à un tiers des effectifs (1 pour 2).",
      "12 agents correspondrait à un ratio 1:4.",
      "18 agents résulte d'un mauvais découpage des parts."
    ],
    explanation: "Le ratio comprend 4 parts égales (1 + 3). Une part vaut 60 / 4 = 15 agents. Il y a donc 15 contractuels et 45 fonctionnaires.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-093",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 75,
    prompt: "Le nombre de visites d'usagers au guichet passe de 1 600 en mars à 1 840 en avril. Quel est le taux de progression constaté ?",
    stimulus: "Fréquentation du guichet multiservices communal :\nMars : 1 600 visites enregistrées.\nAvril : 1 840 visites enregistrées.",
    options: ["+15,0 %", "+12,0 %", "+18,0 %", "+14,0 %"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (1 840 - 1 600) / 1 600 = 240 / 1 600 = +0,15 soit +15,0 %.",
      "+12,0 % correspondrait à 1 792 visites (+192).",
      "+18,0 % correspondrait à 1 888 visites (+288).",
      "+14,0 % est un calcul inexact."
    ],
    explanation: "Taux de progression = (1 840 - 1 600) / 1 600 = 240 / 1 600 = +15,0 %.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-094",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 80,
    prompt: "Un abonnement logiciel annuel de 12 000 euros hors taxes augmente de 5,0 % l'an prochain et reste soumis au taux de TVA de 17,0 %. Quel sera le nouveau coût annuel TTC ?",
    stimulus: "Licences d'exploitation d'un logiciel de gestion documentaire :\nCoût actuel HT : 12 000 euros.\nHausse tarifaire contractuelle : +5,0 %.\nTaux de TVA : 17,0 %.",
    options: ["14 742 euros", "14 500 euros", "14 850 euros", "14 200 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : nouveau prix HT = 12 000 × 1,05 = 12 600 euros ; Nouveau coût TTC = 12 600 × 1,17 = 14 742 euros.",
      "14 500 euros omet la TVA sur les 600 euros de hausse.",
      "14 850 euros surestime le résultat final.",
      "14 200 euros applique une base de calcul erronée."
    ],
    explanation: "Prix révisé HT = 12 000 × 1,05 = 12 600 euros. Avec 17 % de TVA : 12 600 × 1,17 = 14 742 euros TTC.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-095",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "operations-simples",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 65,
    prompt: "Un fonctionnaire effectue un trajet professionnel aller-retour de 140 kilomètres. Si l'indemnité kilométrique légale est fixée à 0,40 euro par kilomètre, quel montant perçoit-il ?",
    stimulus: "Frais de déplacement professionnel :\nDistance totale parcourue : 140 kilomètres.\nBarème kilométrique officiel d'indemnisation : 0,40 euro par kilomètre.",
    options: ["56,00 euros", "52,00 euros", "60,00 euros", "48,00 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 140 × 0,40 = 56,00 euros.",
      "52,00 euros correspondrait à 130 kilomètres.",
      "60,00 euros correspondrait à 150 kilomètres.",
      "48,00 euros correspondrait à un barème de 0,34 euro/km."
    ],
    explanation: "Montant indemnisé = 140 × 0,40 = 56,00 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-096",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "moyenne",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Quelle est la consommation moyenne trimestrielle de rames de papier d'une administration ?",
    stimulus: "Suivi logistique annuel des fournitures :\nTrimestre 1 : 180 rames.\nTrimestre 2 : 220 rames.\nTrimestre 3 : 140 rames.\nTrimestre 4 : 260 rames.",
    options: ["200 rames", "190 rames", "210 rames", "195 rames"],
    correctIndex: 0,
    optionRationales: [
      "Correct : (180 + 220 + 140 + 260) / 4 = 800 / 4 = 200 rames par trimestre.",
      "190 rames sous-estime la moyenne.",
      "210 rames surestime la moyenne.",
      "195 rames résulte d'une erreur d'addition."
    ],
    explanation: "Total annuel = 180 + 220 + 140 + 260 = 800 rames. Consommation moyenne trimestrielle = 800 / 4 = 200 rames.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-097",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "ratio-proportion",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Une enveloppe de 63 000 euros est partagée entre deux actions éducatives dans le ratio 4:3. Quelle est la part de l'action principale ?",
    stimulus: "Projets pédagogiques extrascolaires communaux :\nBudget total : 63 000 euros.\nClé de ventilation Action A : Action B = 4 : 3.",
    options: ["36 000 euros", "27 000 euros", "32 000 euros", "40 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : total parts = 4 + 3 = 7. Une part = 63 000 / 7 = 9 000 euros. Action A = 4 × 9 000 = 36 000 euros.",
      "27 000 euros correspond à l'action secondaire B (3 parts).",
      "32 000 euros ne correspond pas à la proportion 4:3.",
      "40 000 euros surestime la part de l'action A."
    ],
    explanation: "Total parts = 7. Chaque part vaut 63 000 / 7 = 9 000 euros. L'action principale (4 parts) reçoit 4 × 9 000 = 36 000 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-098",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "variation",
    difficulty: 3,
    language: "fr",
    estimatedSeconds: 85,
    prompt: "Le coût annuel d'entretien d'un parc informatique s'élève à 80 000 euros l'an 1. Il augmente de 10 % l'an 2, puis subit une renégociation entraînant une baisse de 10 % l'an 3. Quel est son montant final en an 3 ?",
    stimulus: "Marché pluriannuel de maintenance technique des serveurs :\nAnnée 1 : 80 000 euros.\nAnnée 2 : hausse contractuelle de +10,0 %.\nAnnée 3 : renégociation entraînant une baisse de -10,0 %.",
    options: ["79 200 euros", "80 000 euros", "81 000 euros", "78 500 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : an 2 = 80 000 × 1,10 = 88 000 euros ; an 3 = 88 000 × 0,90 = 79 200 euros.",
      "80 000 euros supposerait à tort qu'une hausse de 10 % et une baisse de 10 % s'annulent.",
      "81 000 euros surestime le résultat net.",
      "78 500 euros sous-estime le résultat."
    ],
    explanation: "Multiplicateur composé = 1,10 × 0,90 = 0,99. Coût final en an 3 = 80 000 × 0,99 = 79 200 euros (perte nette de 1 %).",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-099",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "pourcentage",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 70,
    prompt: "Sur une enveloppe globale de subvention de 350 000 euros, 60 % sont décaissés au premier semestre et 25 % au troisième trimestre. Quel montant reste à décaisser au quatrième trimestre ?",
    stimulus: "Calendrier de décaissement d'une aide d'État :\nEnveloppe totale approuvée : 350 000 euros.\nDécaissement S1 : 60 %.\nDécaissement T3 : 25 %.",
    options: ["52 500 euros", "50 000 euros", "55 000 euros", "48 000 euros"],
    correctIndex: 0,
    optionRationales: [
      "Correct : part restante = 100 % - (60 % + 25 %) = 15 % ; 350 000 × 0,15 = 52 500 euros.",
      "50 000 euros est un montant arrondi inexact.",
      "55 000 euros surestime le reliquat.",
      "48 000 euros sous-estime le solde à décaisser."
    ],
    explanation: "Part résiduelle au T4 = 100 % - 85 % = 15 %. Montant restant = 350 000 × 0,15 = 52 500 euros.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  },
  {
    id: "numeric-calc-100",
    version: 1,
    category: "numeric",
    itemFormat: "single_best",
    skill: "operations-simples",
    difficulty: 2,
    language: "fr",
    estimatedSeconds: 65,
    prompt: "Un agent instructeur traite 15 dossiers par jour ouvré. Combien de dossiers aura-t-il traités au cours d'un mois comptant 22 jours ouvrés ?",
    stimulus: "Rendement opérationnel d'un instructeur de demandes administratives :\nCadence moyenne : 15 dossiers traités par jour ouvré.\nNombre de jours ouvrés du mois : 22 jours.",
    options: ["330 dossiers", "320 dossiers", "340 dossiers", "315 dossiers"],
    correctIndex: 0,
    optionRationales: [
      "Correct : 22 × 15 = 22 × 10 + 22 × 5 = 220 + 110 = 330 dossiers.",
      "320 dossiers sous-estime le total mensuel.",
      "340 dossiers surestime le total mensuel.",
      "315 dossiers correspondrait à 21 jours d'activité."
    ],
    explanation: "Multiplication directe : 22 jours × 15 dossiers/jour = 330 dossiers traités sur le mois.",
    sourceType: "original_ai_assisted",
    reviewStatus: "approved",
    createdAt: NOW,
    reviewer: REVIEWER,
    reviewedAt: NOW
  }
];
